### Perform Exploratory Data Analysis (EDA) and discuss the data and what you observe prior to beginning modeling and how impact how to proceed ###

In [4]:
import pandas as pd
import numpy as np

df = pd.read_csv('8k_diabetes.csv')

In [5]:
df.shape

(8000, 51)

Since there are 51 columns, I will transponse the first 10 rows to see a preview of the data

In [ ]:
df.head(10).T

In [18]:
# Checking the counts and Data types of each column 
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8000 entries, 0 to 7999
Data columns (total 51 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   race                      8000 non-null   object
 1   gender                    8000 non-null   object
 2   age                       8000 non-null   object
 3   weight                    8000 non-null   object
 4   admission_type_id         7424 non-null   object
 5   discharge_disposition_id  7627 non-null   object
 6   admission_source_id       7250 non-null   object
 7   time_in_hospital          8000 non-null   int64
 8   payer_code                8000 non-null   object
 9   medical_specialty         8000 non-null   object
 10  num_lab_procedures        8000 non-null   int64
 11  num_procedures            8000 non-null   int64
 12  num_medications           8000 non-null   int64
 13  number_outpatient         8000 non-null   int64
 14  number_emergency          8000 non-null   int64
 15  number_inpatient          8000 non-null   int64
 16  diag_1                    8000 non-null   object
 17  diag_2                    8000 non-null   object
 18  diag_3                    8000 non-null   object
 19  number_diagnoses          8000 non-null   int64
 20  max_glu_serum             8000 non-null   object
 21  A1Cresult                 8000 non-null   object
 22  metformin                 8000 non-null   object
 23  repaglinide               8000 non-null   object
 24  nateglinide               8000 non-null   object
 25  chlorpropamide            8000 non-null   object
 26  glimepiride               8000 non-null   object
 27  acetohexamide             8000 non-null   object
 28  glipizide                 8000 non-null   object
 29  glyburide                 8000 non-null   object
 30  tolbutamide               8000 non-null   object
 31  pioglitazone              8000 non-null   object
 32  rosiglitazone             8000 non-null   object
 33  acarbose                  8000 non-null   object
 34  miglitol                  8000 non-null   object
 35  troglitazone              8000 non-null   object
 36  tolazamide                8000 non-null   object
 37  examide                   8000 non-null   object
 38  citoglipton               8000 non-null   object
 39  insulin                   8000 non-null   object
 40  glyburide.metformin       8000 non-null   object
 41  glipizide.metformin       8000 non-null   object
 42  glimepiride.pioglitazone  8000 non-null   object
 43  metformin.rosiglitazone   8000 non-null   object
 44  metformin.pioglitazone    8000 non-null   object
 45  change                    8000 non-null   object
 46  diabetesMed               8000 non-null   object
 47  readmitted                8000 non-null   bool
 48  diag_1_desc               8000 non-null   object
 49  diag_2_desc               7945 non-null   object
 50  diag_3_desc               7825 non-null   object
dtypes: bool(1), int64(8), object(42)
memory usage: 3.1+ MB

In [7]:
# Checking null values in all the columns 

df.isnull().sum()

race                          0
gender                        0
age                           0
weight                        0
admission_type_id           576
discharge_disposition_id    373
admission_source_id         750
time_in_hospital              0
payer_code                    0
medical_specialty             0
num_lab_procedures            0
num_procedures                0
num_medications               0
number_outpatient             0
number_emergency              0
number_inpatient              0
diag_1                        0
diag_2                        0
diag_3                        0
number_diagnoses              0
max_glu_serum                 0
A1Cresult                     0
metformin                     0
repaglinide                   0
nateglinide                   0
chlorpropamide                0
glimepiride                   0
acetohexamide                 0
glipizide                     0
glyburide                     0
tolbutamide                   0
pioglitazone                  0
rosiglitazone                 0
acarbose                      0
miglitol                      0
troglitazone                  0
tolazamide                    0
examide                       0
citoglipton                   0
insulin                       0
glyburide.metformin           0
glipizide.metformin           0
glimepiride.pioglitazone      0
metformin.rosiglitazone       0
metformin.pioglitazone        0
change                        0
diabetesMed                   0
readmitted                    0
diag_1_desc                   0
diag_2_desc                  55
diag_3_desc                 175
dtype: int64

In [21]:
#df['admission_type_id'].isnull().sum()

# I decided to replace the null values in the following columns because the data on these rows can be important

df['admission_type_id'].fillna("?", inplace = True)
df['discharge_disposition_id'].fillna("?", inplace = True)
df['admission_source_id'].fillna("?", inplace = True)
df['diag_2_desc'].fillna("", inplace = True)
df['diag_3_desc'].fillna("", inplace = True)

In [22]:
# This loop will print the unique classes of each column 

print("All classes by column")
for column in df.columns:
    print(column)
    print(df[column].drop_duplicates())

All classes by column
race
0            Caucasian
3      AfricanAmerican
13            Hispanic
49               Other
91               Asian
132                  ?
Name: race, dtype: object
gender
0    Female
2      Male
Name: gender, dtype: object
age
0       [50-60)
1       [20-30)
2       [80-90)
5       [70-80)
6       [60-70)
16      [30-40)
20      [40-50)
25      [10-20)
29     [90-100)
276      [0-10)
Name: age, dtype: object
weight
0               ?
1         [50-75)
54       [75-100)
62      [100-125)
233     [150-175)
260        [0-25)
660     [125-150)
1279      [25-50)
Name: weight, dtype: object
admission_type_id
0            Elective
1              Urgent
2       Not Available
3           Emergency
8                   ?
242        Not Mapped
6953          Newborn
Name: admission_type_id, dtype: object
discharge_disposition_id
0                                      Discharged to home
2       Discharged/transferred to home with home healt...
6                                                 Expired
10      Discharged/transferred to a long term care hos...
11                          Discharged/transferred to SNF
16      Discharged/transferred to another  type of inp...
19                                             Not Mapped
37      Discharged/transferred to another short term h...
41                                                      ?
108                                              Left AMA
123     Discharged/transferred to another rehab fac in...
153                            Hospice / medical facility
164                                        Hospice / home
186     Discharged/transferred/referred to a psychiatr...
227                         Discharged/transferred to ICF
576     Discharged/transferred to home under care of H...
907             Admitted as an inpatient to this hospital
2304    Discharged/transferred/referred another instit...
4304    Discharged/transferred to a federal health car...
6089    Discharged/transferred within this institution...
6207    Discharged/transferred/referred to this instit...
7893    Discharged/transferred to a nursing facility c...
Name: discharge_disposition_id, dtype: object
admission_source_id
0                                   Physician Referral
2                                                    ?
3           Transfer from another health care facility
4                                       Emergency Room
14      Transfer from a Skilled Nursing Facility (SNF)
21                            Transfer from a hospital
56                                          Not Mapped
60                                     Clinic Referral
169                                       HMO Referral
1891                                     Not Available
7608                             Court/Law Enforcement
Name: admission_source_id, dtype: object
time_in_hospital
0      1
1      2
2      7
3      4
4      5
6      6
8      3
10    14
12    10
18     8
28    11
33    12
35     9
40    13
Name: time_in_hospital, dtype: int64
payer_code
0       CP
1       UN
2       MC
4        ?
12      HM
20      SP
27      CM
31      BC
143     MD
201     WC
218     OG
277     PO
329     DM
863     SI
2882    OT
2921    CH
Name: payer_code, dtype: object
medical_specialty
0                              Surgery-Neuro
1                                          ?
2                     Family/GeneralPractice
4                                 Psychiatry
5                                 Cardiology
6                           InternalMedicine
9            Surgery-Cardiovascular/Thoracic
19                                Nephrology
20                          Emergency/Trauma
23                          Gastroenterology
24                               Orthopedics
25                      Cardiology-Pediatric
28         PhysicalMedicineandRehabilitation
32                                Gynecology
37                               Pulmonology
62                           Surgery-General
75                                Pediatrics
87                Orthopedics-Reconstructive
120                        Surgery-Pediatric
162                           Otolaryngology
276                  Pediatrics-CriticalCare
284                      Hematology/Oncology
315                  ObstetricsandGynecology
351                 Pediatrics-Endocrinology
360                         Surgery-Vascular
374                                  Urology
441                                Neurology
469                              Radiologist
537                                Osteopath
595                   Surgery-Cardiovascular
612                               Psychology
617                                 Oncology
712                            Endocrinology
874                         OutreachServices
1035                                Podiatry
1099                           Ophthalmology
1313                             Hospitalist
1376                               Radiology
1401    Obsterics&Gynecology-GynecologicOnco
1551                        Surgery-Thoracic
2495                                 Surgeon
2613                               Pathology
2624                         Surgery-Plastic
3056                      InfectiousDiseases
3712                Anesthesiology-Pediatric
4973                  Pediatrics-Pulmonology
5222          Pediatrics-Hematology-Oncology
6996                              Hematology
7307                    Surgery-Colon&Rectal
7558        Surgery-PlasticwithinHeadandNeck
7690            Pediatrics-EmergencyMedicine
7709                              Obstetrics
Name: medical_specialty, dtype: object
num_lab_procedures
0        35
1         8
2        12
3        33
4        31
       ...
4749    109
4937     93
5570    113
6046    107
7114     88
Name: num_lab_procedures, Length: 108, dtype: int64
num_procedures
0     4
1     5
2     0
3     1
9     2
15    3
46    6
Name: num_procedures, dtype: int64
num_medications
0       21
1        5
4       13
5       10
6       20
        ..
5707    53
6025    74
6405    81
6416    55
7042    65
Name: num_medications, Length: 68, dtype: int64
number_outpatient
0        0
7        2
44       1
119      4
216      3
233      7
261      5
389      6
547     19
594     13
684      8
884     18
982      9
1364    10
2646    16
3051    17
4933    12
5383    36
6038    14
6433    27
7215    11
7565    21
Name: number_outpatient, dtype: int64
number_emergency
0        0
7        1
19       2
86       3
957      4
2404     6
2520    42
2833     5
3254     7
3860     8
5734    13
Name: number_emergency, dtype: int64
number_inpatient
0       0
2       1
13      2
19      4
45      3
355     7
446     5
447     6
1904    9
2550    8
Name: number_inpatient, dtype: int64
diag_1
0       723
1       664
2       481
3       682
4       296
       ...
7492    921
7571    794
7581    814
7824    643
7873    822
Name: diag_1, Length: 423, dtype: object
diag_2
0          723
1          648
2          428
3           41
4       250.01
         ...
7621       258
7685        34
7821       V49
7849       681
7856       365
Name: diag_2, Length: 405, dtype: object
diag_3
0       719
1       285
2       276
3       250
4       298
       ...
7727    360
7765    372
7885    845
7918    862
7973      5
Name: diag_3, Length: 431, dtype: object
number_diagnoses
0      9
1      6
3      3
4      7
5      8
9      5
24     4
25     2
276    1
Name: number_diagnoses, dtype: int64
max_glu_serum
0     None
2     >200
19    Norm
53    >300
Name: max_glu_serum, dtype: object
A1Cresult
0     None
7     Norm
10      >7
13      >8
Name: A1Cresult, dtype: object
metformin
0          No
4      Steady
10       Down
119        Up
Name: metformin, dtype: object
repaglinide
0           No
227     Steady
663         Up
1632      Down
Name: repaglinide, dtype: object
nateglinide
0           No
183     Steady
3679      Down
6085        Up
Name: nateglinide, dtype: object
chlorpropamide
0           No
433     Steady
4443        Up
Name: chlorpropamide, dtype: object
glimepiride
0          No
17     Steady
57         Up
268      Down
Name: glimepiride, dtype: object
acetohexamide
0    No
Name: acetohexamide, dtype: object
glipizide
0          No
4      Steady
13         Up
123      Down
Name: glipizide, dtype: object
glyburide
0          No
10     Steady
61       Down
101        Up
Name: glyburide, dtype: object
tolbutamide
0         No
64    Steady
Name: tolbutamide, dtype: object
pioglitazone
0          No
22     Steady
125        Up
408      Down
Name: pioglitazone, dtype: object
rosiglitazone
0          No
28     Steady
57         Up
655      Down
Name: rosiglitazone, dtype: object
acarbose
0           No
182     Steady
6311        Up
Name: acarbose, dtype: object
miglitol
0           No
918     Steady
7086      Down
Name: miglitol, dtype: object
troglitazone
0    No
Name: troglitazone, dtype: object
tolazamide
0           No
4698    Steady
Name: tolazamide, dtype: object
examide
0    No
Name: examide, dtype: object
citoglipton
0    No
Name: citoglipton, dtype: object
insulin
0         No
2     Steady
10      Down
25        Up
Name: insulin, dtype: object
glyburide.metformin
0           No
116     Steady
2737      Down
3559        Up
Name: glyburide.metformin, dtype: object
glipizide.metformin
0           No
4105    Steady
Name: glipizide.metformin, dtype: object
glimepiride.pioglitazone
0    No
Name: glimepiride.pioglitazone, dtype: object
metformin.rosiglitazone
0    No
Name: metformin.rosiglitazone, dtype: object
metformin.pioglitazone
0    No
Name: metformin.pioglitazone, dtype: object
change
0    No
4    Ch
Name: change, dtype: object
diabetesMed
0     No
2    Yes
Name: diabetesMed, dtype: object
readmitted
0    False
2     True
Name: readmitted, dtype: bool
diag_1_desc
0                      Spinal stenosis in cervical region
1       First-degree perineal laceration, unspecified ...
2       Pneumococcal pneumonia [Streptococcus pneumoni...
3                          Cellulitis and abscess of face
4       Bipolar I disorder, single manic episode, unsp...
                              ...
7492                   Black eye, not otherwise specified
7571    Abnormal function study of brain and central n...
7581          Closed fracture of carpal bone, unspecified
7824    Mild hyperemesis gravidarum, unspecified as to...
7873                           Closed fracture of patella
Name: diag_1_desc, Length: 423, dtype: object
diag_2_desc
0                      Spinal stenosis in cervical region
1       Diabetes mellitus of mother, complicating preg...
2                   Congestive heart failure, unspecified
3       Streptococcus infection in conditions classifi...
4       Diabetes mellitus without mention of complicat...
                              ...
7621    Polyglandular activity in multiple endocrine a...
7685                            Streptococcal sore throat
7821                                Deficiencies of limbs
7849        Cellulitis and abscess of finger, unspecified
7856                             Preglaucoma, unspecified
Name: diag_2_desc, Length: 405, dtype: object
diag_3_desc
0                     Effusion of joint, site unspecified
1                                    Sideroblastic anemia
2                    Hyperosmolality and/or hypernatremia
3       Diabetes mellitus without mention of complicat...
4                               Depressive type psychosis
                              ...
7727                Purulent endophthalmitis, unspecified
7765                    Acute conjunctivitis, unspecified
7885                    Sprain of ankle, unspecified site
7918    Injury to diaphragm, without mention of open w...
7973                        Staphylococcal food poisoning
Name: diag_3_desc, Length: 431, dtype: object

In the dataset '?' represents mission values.
This code will show the count of '?' in all the columns.

In [16]:
for col in df.columns:
    if df[col].dtype == object:
         print(col,df[col][df[col] == '?'].count())

race 180
gender 0
age 0
weight 7675
admission_type_id 0
discharge_disposition_id 0
admission_source_id 0
payer_code 4260
medical_specialty 3229
diag_1 0
diag_2 55
diag_3 175
max_glu_serum 0
A1Cresult 0
metformin 0
repaglinide 0
nateglinide 0
chlorpropamide 0
glimepiride 0
acetohexamide 0
glipizide 0
glyburide 0
tolbutamide 0
pioglitazone 0
rosiglitazone 0
acarbose 0
miglitol 0
troglitazone 0
tolazamide 0
examide 0
citoglipton 0
insulin 0
glyburide.metformin 0
glipizide.metformin 0
glimepiride.pioglitazone 0
metformin.rosiglitazone 0
metformin.pioglitazone 0
change 0
diabetesMed 0
diag_1_desc 0
diag_2_desc 0
diag_3_desc 0

In [17]:
print("All value counts by column")
for column in df.columns:
    print(column,"\n")
    
    print(df[column].value_counts(),"\n")

All value counts by column
race

Caucasian          5891
AfricanAmerican    1639
?                   180
Hispanic            146
Other               101
Asian                43
Name: race, dtype: int64

gender

Female    4314
Male      3686
Name: gender, dtype: int64

age

[70-80)     2049
[60-70)     1749
[50-60)     1391
[80-90)     1248
[40-50)      800
[30-40)      340
[90-100)     214
[20-30)      117
[10-20)       65
[0-10)        27
Name: age, dtype: int64

weight

?            7675
[75-100)      138
[50-75)        95
[100-125)      61
[125-150)      12
[25-50)        10
[0-25)          5
[150-175)       4
Name: weight, dtype: int64

admission_type_id

Emergency        3968
Urgent           1545
Elective         1401
Not Available     476
Not Mapped         33
Newborn             1
Name: admission_type_id, dtype: int64

discharge_disposition_id

Discharged to home                                                                                             4879
Discharged/transferred to SNF                                                                                   948
Discharged/transferred to home with home health service                                                         912
Discharged/transferred to another short term hospital                                                           156
Expired                                                                                                         154
Discharged/transferred to another rehab fac including rehab units of a hospital.                                140
Discharged/transferred to another  type of inpatient care institution                                           111
Not Mapped                                                                                                       99
Discharged/transferred to ICF                                                                                    75
Discharged/transferred to a long term care hospital.                                                             40
Left AMA                                                                                                         33
Hospice / home                                                                                                   29
Hospice / medical facility                                                                                       24
Discharged/transferred to home under care of Home IV provider                                                    12
Discharged/transferred/referred to a psychiatric hospital of a psychiatric distinct part unit of a hospital       8
Discharged/transferred within this institution to Medicare approved swing bed                                     2
Admitted as an inpatient to this hospital                                                                         1
Discharged/transferred/referred another institution for outpatient services                                       1
Discharged/transferred to a federal health care facility.                                                         1
Discharged/transferred/referred to this institution for outpatient services                                       1
Discharged/transferred to a nursing facility certified under Medicaid but not certified under Medicare            1
Name: discharge_disposition_id, dtype: int64

admission_source_id

Emergency Room                                    3969
Physician Referral                                2387
Transfer from a hospital                           322
Transfer from another health care facility         286
Clinic Referral                                    134
Transfer from a Skilled Nursing Facility (SNF)      93
HMO Referral                                        29
Not Mapped                                          16
Not Available                                       13
Court/Law Enforcement                                1
Name: admission_source_id, dtype: int64

time_in_hospital

2     1367
3     1333
1     1141
4     1041
5      799
6      618
7      480
8      329
9      238
10     185
11     156
12     135
13      90
14      88
Name: time_in_hospital, dtype: int64

payer_code

?     4260
MC    2014
HM     373
BC     308
SP     234
UN     232
MD     188
CP     161
CM      82
DM      43
PO      38
OG      37
WC       9
SI       8
CH       8
OT       5
Name: payer_code, dtype: int64

medical_specialty

?                                       3229
InternalMedicine                        1562
Family/GeneralPractice                   698
Cardiology                               580
Emergency/Trauma                         407
Surgery-General                          257
Orthopedics-Reconstructive               140
Nephrology                               126
Orthopedics                              106
Psychiatry                                96
Surgery-Cardiovascular/Thoracic           80
Pulmonology                               78
ObstetricsandGynecology                   78
Surgery-Neuro                             70
Urology                                   64
Surgery-Vascular                          57
Gastroenterology                          50
Radiologist                               42
PhysicalMedicineandRehabilitation         35
Oncology                                  32
Pediatrics                                29
Neurology                                 22
Pediatrics-Endocrinology                  19
Endocrinology                             15
Pediatrics-CriticalCare                   14
Hematology/Oncology                       13
Otolaryngology                            11
Surgery-Thoracic                          11
Surgery-Cardiovascular                    11
Podiatry                                   8
Radiology                                  7
Psychology                                 6
Gynecology                                 6
Surgery-Plastic                            5
Osteopath                                  4
Obsterics&Gynecology-GynecologicOnco       4
Surgery-Pediatric                          4
Cardiology-Pediatric                       3
Ophthalmology                              3
Anesthesiology-Pediatric                   2
InfectiousDiseases                         2
Pathology                                  2
Surgeon                                    2
Hospitalist                                2
OutreachServices                           1
Pediatrics-Pulmonology                     1
Pediatrics-Hematology-Oncology             1
Hematology                                 1
Surgery-Colon&Rectal                       1
Surgery-PlasticwithinHeadandNeck           1
Pediatrics-EmergencyMedicine               1
Obstetrics                                 1
Name: medical_specialty, dtype: int64

num_lab_procedures

43     231
1      202
44     200
45     199
46     189
      ...
120      1
104      1
98       1
108      1
103      1
Name: num_lab_procedures, Length: 108, dtype: int64

num_procedures

0    3484
1    1672
2    1020
3     840
6     381
4     335
5     268
Name: num_procedures, dtype: int64

num_medications

11    497
12    476
15    453
14    446
13    442
     ...
75      1
74      1
81      1
58      1
65      1
Name: num_medications, Length: 68, dtype: int64

number_outpatient

0     6956
1      567
2      219
3      111
4       58
5       36
6       16
7        7
9        6
10       6
8        5
13       2
14       2
36       1
11       1
27       1
18       1
12       1
17       1
16       1
19       1
21       1
Name: number_outpatient, dtype: int64

number_emergency

0     7389
1      462
2       92
3       31
4       11
8        4
6        3
5        3
7        3
42       1
13       1
Name: number_emergency, dtype: int64

number_inpatient

0    6045
1    1295
2     408
3     149
4      54
5      29
6      10
7       5
9       3
8       2
Name: number_inpatient, dtype: int64

diag_1

414    602
428    500
786    363
410    336
486    252
      ...
680      1
361      1
395      1
619      1
822      1
Name: diag_1, Length: 423, dtype: int64

diag_2

250     553
276     532
428     525
427     423
401     317
       ...
967       1
E941      1
382       1
824       1
365       1
Name: diag_2, Length: 405, dtype: int64

diag_3

250    1022
401     787
276     359
428     318
427     303
       ...
265       1
717       1
825       1
580       1
5         1
Name: diag_3, Length: 431, dtype: int64

number_diagnoses

9    3096
5    1208
6     947
7     906
8     843
4     564
3     285
2     120
1      31
Name: number_diagnoses, dtype: int64

max_glu_serum

None    7475
Norm     270
>200     153
>300     102
Name: max_glu_serum, dtype: int64

A1Cresult

None    6709
>8       638
Norm     368
>7       285
Name: A1Cresult, dtype: int64

metformin

No        6409
Steady    1460
Up          90
Down        41
Name: metformin, dtype: int64

repaglinide

No        7888
Steady      96
Up          11
Down         5
Name: repaglinide, dtype: int64

nateglinide

No        7962
Steady      36
Down         1
Up           1
Name: nateglinide, dtype: int64

chlorpropamide

No        7990
Steady       9
Up           1
Name: chlorpropamide, dtype: int64

glimepiride

No        7604
Steady     359
Up          28
Down         9
Name: glimepiride, dtype: int64

acetohexamide

No    8000
Name: acetohexamide, dtype: int64

glipizide

No        6938
Steady     946
Up          76
Down        40
Name: glipizide, dtype: int64

glyburide

No        7029
Steady     838
Up          79
Down        54
Name: glyburide, dtype: int64

tolbutamide

No        7998
Steady       2
Name: tolbutamide, dtype: int64

pioglitazone

No        7440
Steady     523
Up          24
Down        13
Name: pioglitazone, dtype: int64

rosiglitazone

No        7393
Steady     587
Up          11
Down         9
Name: rosiglitazone, dtype: int64

acarbose

No        7976
Steady      23
Up           1
Name: acarbose, dtype: int64

miglitol

No        7997
Steady       2
Down         1
Name: miglitol, dtype: int64

troglitazone

No    8000
Name: troglitazone, dtype: int64

tolazamide

No        7999
Steady       1
Name: tolazamide, dtype: int64

examide

No    8000
Name: examide, dtype: int64

citoglipton

No    8000
Name: citoglipton, dtype: int64

insulin

No        4112
Steady    2457
Down       755
Up         676
Name: insulin, dtype: int64

glyburide.metformin

No        7956
Steady      42
Down         1
Up           1
Name: glyburide.metformin, dtype: int64

glipizide.metformin

No        7998
Steady       2
Name: glipizide.metformin, dtype: int64

glimepiride.pioglitazone

No    8000
Name: glimepiride.pioglitazone, dtype: int64

metformin.rosiglitazone

No    8000
Name: metformin.rosiglitazone, dtype: int64

metformin.pioglitazone

No    8000
Name: metformin.pioglitazone, dtype: int64

change

No    4580
Ch    3420
Name: change, dtype: int64

diabetesMed

Yes    6014
No     1986
Name: diabetesMed, dtype: int64

readmitted

False    4822
True     3178
Name: readmitted, dtype: int64

diag_1_desc

Coronary atherosclerosis of unspecified type of vessel, native or graft           602
Congestive heart failure, unspecified                                             500
Respiratory abnormality, unspecified                                              363
Acute myocardial infarction of anterolateral wall, episode of care unspecified    336
Pneumonia, organism unspecified                                                   252
                                                                                 ...
Carbuncle and furuncle of face                                                      1
Retinal detachment with retinal defect, unspecified                                 1
Rheumatic aortic stenosis                                                           1
Urinary-genital tract fistula, female                                               1
Closed fracture of patella                                                          1
Name: diag_1_desc, Length: 423, dtype: int64

diag_2_desc

Diabetes mellitus without mention of complication, type II or unspecified type, not stated as uncontrolled    553
Hyperosmolality and/or hypernatremia                                                                          532
Congestive heart failure, unspecified                                                                         525
Paroxysmal supraventricular tachycardia                                                                       423
Malignant essential hypertension                                                                              317
                                                                                                             ...
Arthropathy associated with other endocrine and metabolic disorders                                             1
Poisoning by barbiturates                                                                                       1
Parasympathomimetics [cholinergics] causing adverse effects in therapeutic use                                  1
Contact dermatitis and other eczema due to detergents                                                           1
Preglaucoma, unspecified                                                                                        1
Name: diag_2_desc, Length: 404, dtype: int64

diag_3_desc

Diabetes mellitus without mention of complication, type II or unspecified type, not stated as uncontrolled                 1022
Malignant essential hypertension                                                                                            787
Hyperosmolality and/or hypernatremia                                                                                        359
Congestive heart failure, unspecified                                                                                       318
Paroxysmal supraventricular tachycardia                                                                                     303
                                                                                                                           ...
Acute pharyngitis                                                                                                             1
Overanxious disorder specific to childhood and adolescence                                                                    1
Subarachnoid hemorrhage following injury without mention of open intracranial wound, unspecified state of consciousness       1
Fracture of calcaneus, closed                                                                                                 1
Staphylococcal food poisoning                                                                                                 1
Name: diag_3_desc, Length: 430, dtype: int64

### Pre-processed categorical data for use in the model and justified pre-processing method. Note this may be different for each algorithm you try ###

Drop the columns with a large count of missing values and where the majority of categories are only one value

In [ ]:
# Drop weight, payer_code, medical_specialty because they have a large number of missing values

df = df.drop(['weight','payer_code','medical_specialty'], axis = 1)

In [ ]:
#acetohexamide,examide,citoglipton,Troglitazone, glimepiride.pioglitazone, metformin.rosiglitazone ,metformin.pioglitazone 

#In the following columns, there are 2 or 3 classes, however one of them has the majority of values

#Tolbutamide, glipizide.metformin 
#- The great majority of the data is NO, 7998. Only 2 are Steady
df = df.drop(['tolbutamide', 'glipizide.metformin'], axis = 1)
#Tolazamide
#- The great majority of the data is NO, 7999. Only 1 is Steady
df = df.drop(['tolazamide'], axis = 1)
#Miglitol
#- The great majority is NO 7997, Steady 2 and Down 1
df = df.drop(['miglitol'], axis = 1)

#Acarbose
#- The majority is NO 7976, Steady 23 and Up 1
df = df.drop(['acarbose'], axis = 1)

#Chlorpropamide
#- No 7990, Steady 9, Up 1
df = df.drop(['chlorpropamide'], axis = 1)

#Nateglinide
#- No 7962, Steady 36, Down 1, Up 1
df = df.drop(['nateglinide'], axis = 1)

#Repaglinide
#- No 7888, Steady 96, Up 11, Down 5
df = df.drop(['repaglinide'], axis = 1)

#acetohexamide has only one value for all rows
df = df.drop(['acetohexamide'], axis =1)

### Pre-processed numerical data appropriately including handling missing data and justified methods used. Note this may be different for each algorithm you try.

The value '?' means that the data is missing. Race, diag_2 and diag_3 contain '?' values, so I'll remove those records

In [ ]:
drop_Idx = set(df[(df['diag_2'] == '?') & (df['diag_3'] == '?')].index)

#Race, diage_2, diag_3
#- Drop missing values

drop_Idx = drop_Idx.union(set(df['diag_2'][df['diag_2'] == '?'].index))
drop_Idx = drop_Idx.union(set(df['diag_3'][df['diag_3'] == '?'].index))
drop_Idx = drop_Idx.union(set(df['race'][df['race'] == '?'].index))

#- Drop these columns because they contain only one value, and it's not representative
#Discharge Disposition Id
#- Drop expired, they can't be readmited

drop_Idx = drop_Idx.union(set(df['discharge_disposition_id'][df['discharge_disposition_id'] == 'Expired'].index))

new_Idx = list(set(df.index) - set(drop_Idx))
df = df.iloc[new_Idx]

### Implement a model to make predictions using text data using tf-idf

In [ ]:
df.head(10).T

In [23]:
df['discharge_disposition_id'].drop_duplicates()

0                                      Discharged to home
2       Discharged/transferred to home with home healt...
6                                                 Expired
10      Discharged/transferred to a long term care hos...
11                          Discharged/transferred to SNF
16      Discharged/transferred to another  type of inp...
19                                             Not Mapped
37      Discharged/transferred to another short term h...
41                                                      ?
108                                              Left AMA
123     Discharged/transferred to another rehab fac in...
153                            Hospice / medical facility
164                                        Hospice / home
186     Discharged/transferred/referred to a psychiatr...
227                         Discharged/transferred to ICF
576     Discharged/transferred to home under care of H...
907             Admitted as an inpatient to this hospital
2304    Discharged/transferred/referred another instit...
4304    Discharged/transferred to a federal health car...
6089    Discharged/transferred within this institution...
6207    Discharged/transferred/referred to this instit...
7893    Discharged/transferred to a nursing facility c...
Name: discharge_disposition_id, dtype: object

In [ ]:
df['diabetesMed'].value_counts()

In [ ]:
# cat_data should contain all the columns with categorical data (all text excel )

#cat_data = df.select_dtypes('O')
cat_data = df.drop(['time_in_hospital','num_lab_procedures','num_procedures','num_medications','number_outpatient','number_emergency','number_inpatient','number_diagnoses','diag_1_desc','diag_2_desc','diag_3_desc'], axis = 1 )

text_data = df[['diag_1_desc','diag_2_desc','diag_3_desc']]

num_data = df.select_dtypes(np.number)

bool_data = df.select_dtypes(bool)

#### Use label encoder for categorical data (this is just a test) ####

In [ ]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

for i in cat_data:
    cat_data[i] = le.fit_transform(cat_data[i])

#### Use TF-IDF here ####

In [ ]:
#%pip install sklearn-pandas
from sklearn_pandas import DataFrameMapper
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(stop_words='english')

text_data_x = vectorizer.fit_transform(text_data)

#vectorizer.get_feature_names_out()


#X = data.drop('readmitted',axis=1)

#y = data['readmitted']

In [ ]:
data = pd.concat([num_data,text_data_x,bool_data],axis=1)

In [25]:
import statsmodels.api as sm

from sklearn.preprocessing import StandardScaler 

from sklearn.model_selection import train_test_split

from sklearn.linear_model import LogisticRegression

from sklearn.pipeline import Pipeline

X = data.drop('readmitted',axis=1)

y = data['readmitted']

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.1,random_state=1)

SC = StandardScaler()

X_train_scaled = pd.DataFrame(SC.fit_transform(X_train),columns=X_train.columns)
X_test_scaled = pd.DataFrame(SC.transform(X_test),columns=X_test.columns)

LR = LogisticRegression()

LR.fit(X_train_scaled,y_train)

LR.score(X_train_scaled,y_train)

NameError: name 'data' is not defined

In [ ]:
LR.score(X_test_scaled,y_test)